spring.profiles: local
logging:
  level:
    com:
      scnl:
        hcms:
          hris: DEBUG
  file: log\app.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] -%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] [%thread] %-5level %logger{40}-%msg%n'
server:
  port: 7443
  servlet:
    context-path: /iman-service
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1527:SCNLUAT1
    username: USER
    password: USER
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        enable_lazy_load_no_trans: true
        proc:
          param_null_passing: true
    show-sql: false
    hibernate:
      ddl-auto: none
      use_sql_comments: true
      format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  task:
    scheduling:
      pool:
        size: 20
  logging:
    level:
      org:
        hibernate:
          type: trace
initiatedFNF: 0 15 15 25 * *